name: Cypress CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest  # Use Linux runner environment

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set Node.js version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.16.0'  # Use the same version of Node.js as on local

      # Install Docker
      - name: Install Docker
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version  # Verify if Docker Compose is installed successfully

      # Start Docker Compose to run Kong services
      - name: Start Kong with Docker Compose
        run: docker-compose -f ./docker-compose/docker-compose.yml up -d

      # Wait until Kong is fully started
      - name: Wait for Kong to be ready
        run: |
          until $(curl --output /dev/null --silent --head --fail http://localhost:8001); do
            printf '.'
            sleep 5
          done

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Run Cypress tests
      - name: Run Cypress tests
        run: npm run test

      # Merge mochawesome reports (mochawesome-merge)
      - name: Merge mochawesome reports
        run: npm run report:merge

      # Generate the final HTML test report
      - name: Generate mochawesome HTML report
        run: npm run report:generate

      # Upload generated test report to GitHub Actions
      - name: Upload mochawesome report
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: cypress/results  # Upload the entire report directory, including report.html and assets

      # Stop Kong services
      - name: Stop Kong services
        run: docker-compose -f ./docker-compose/docker-compose.yml down
